indumentariaonline/urls.py
from django.urls import path, include
from django.contrib import admin

urlpatterns = [
    path("shop/", include("shop.urls")),
    path('admin/', admin.site.urls)
]   

shop/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"), 
    path("contacto", views.contacto, name="contacto"),
    
]

shop/models.py
from django.db import models

class Remera(models.Model):
    marca = models.CharField("Marca", max_length=128)
    TALLES = (
        (1, "XS"), (2, "S"), (3, "M"), (4, "L"), (5, "XL"), (6, "XXL")
    )
    talle = models.PositiveSmallIntegerField("Talle", choices=TALLES)
    color = models.CharField("Color", max_length=128)
    lisa = models.BooleanField("Lisa")
    GENEROS = (
        (1, "Hombre"),
        (2, "Mujer"),
        (3, "Unisex")
    )
    genero = models.PositiveSmallIntegerField("Genero", choices=GENEROS)
    def __str__(self):
        cadena = self.marca + " " + self.color + " " + self.get_talle_display()
        return cadena
    class Meta: 
        verbose_name = 'Remera'
        verbose_name_plural = 'Remeras'
        ordering = ['marca']#ordena las remeras alfabeticamente


    

shop/forms.py
from django.forms import ModelForm
from .models import Remera

class FormularioRemera(ModelForm):
    class Meta:
        model = Remera
        fields = ("marca", "talle", "color", "lisa", "genero")





 

shop/views.py
from django.shortcuts import render
from .models import Remera

def index(request):
    remeras = Remera.objects.all()
    ctx = {"remeras": remeras}
    return render(request, "shop/index.html", ctx)


def contacto(request):
    return render(request, "shop/contacto.html")

shop/templates/shop/base.html
{% load static %} 
<html>
<head>
    <title>
        {% block title %} {% endblock %} 
    </title>
</head>
<a href="{% url 'index' %}">
    <img src="{% static 'shop/logo.png'  %}" >
</a>
<body>
    
   {% block content %}{% endblock %}  <!--generamos un bloque lo que significa que en las
                                        plantillas que extienden o heredan de base.html
                                         se aplicara codigo html donde se marque el bloque
                                         --> 
</body>
    

</html>

shop/templates/shop/contacto.html
{% extends "shop/base.html" %}

{% block title %} Contacto {% endblock%}

{% block content %}
<h1>Contacto</h1>

<p><strong>Direccion</strong>: Av. Le Vayer 1234</p>
<p><strong>Telefono</strong>: +541157614322</p>
<p><strong>Email</strong>: contacto@indumentaria-online.com</p>

<p><a href="{% url 'index'%}">Volver al inicio</a></p>
{% endblock %}

shop/templates/shop/index.html
{% extends "shop/base.html" %}

{% block title %}Pagina Inicial {% endblock %}

{% block content %}
<h1>¡Bienvenido a nuestro sitio!</h1>
<h3>Catalogo</h3>
<table>
    <thead>
        <tr>
            <th>Marca</th>
            <th>Talle</th>
            <th>Color</th>
            <th>Lisa</th>
            <th>Genero</th>
        </tr>
    </thead>
    {% for remera in remeras %}
        <tr>
            <td>{{ remera.marca }}</td>
            <td>{{ remera.get_talle_display  }}</td>
            <td>{{ remera.color }}</td>
            <td>{{ remera.lisa }}</td>
            <td>{{ remera.get_genero_display }}</td>
        </tr>
  {% endfor %}
</table>
<p>
    <a href="{% url 'contacto' %}">Ir a contacto</a>
</p>
{% endblock %}